# Generated by Django 3.0.7 on 2020-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reply', models.CharField(max_length=500)),
            ],
        ),
    ]
